[package]
name = "array-map"
version = "0.1.0"
authors = ["Temitope Alaga <temdog007@yahoo.com>"]
edition = "2018"

[lib]
test = true
bench = true

[dependencies.serde]
version = "1.0.104"
features = ["derive"]
optional = true

[features]
default = []
serialize = ["serde"]
unstable = []